---
# Per environment values which override defaults in approved-premises-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    hosts:
      - approved-premises-test.hmpps.service.justice.gov.uk
    contextColour: green
    tlsSecretName: hmpps-approved-premises-test-cert

  env:
    ENVIRONMENT: test
    APPROVED_PREMISES_API_URL: 'https://approved-premises-api-test.hmpps.service.justice.gov.uk'
    INGRESS_URL: 'https://approved-premises-test.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-dev.prison.service.justice.gov.uk'
    COMMUNITY_ACCOMMODATION_API_SERVICE_NAME: approved-premises
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_RESPONSE: 30000
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_DEADLINE: 30000
    ENABLE_V2_MATCH: true

  allowlist: null

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
